server:
  port: 8090
spring:
  application:
    name: spring-boot-mongodb
  data:
    mongodb:
      #      database: batches
      #      host: cluster0.bexczee.mongodb.net
      #      port: 27017
      #      username: root
      #      password: root
      #      uri: mongodb+srv://root:root@<host>/<database>?retryWrites=true&w=majority
      uri: mongodb+srv://root:root@cluster0.u28byav.mongodb.net/batches?retryWrites=true&w=majority
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG # to see the mongodb queries