server:
  port: 9090
  servlet:
    context-path: /readeasy
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - HEAD
              - OPTIONS
              - PUT
            allowedHeaders:
              - "*"
              - "Authorization"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/admin/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/user/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/rating/**
        - id: read-list-service
          uri: lb://read-list-service
          predicates:
            - Path=/api/v1/readlist/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE