insert into books(book_id,book_name,language,price) values(1,'book1','english',200);
insert into books(book_id,book_name,language,price) values(2,'book2','malayalam',100);
insert into books(book_id,book_name,language,price) values(3,'book3','english',200);
insert into books(book_id,book_name,language,price) values(4,'book4','malayalam',300);
insert into books(book_id,book_name,language,price) values(5,'book5','english',400);
insert into books(book_id,book_name,language,price) values(6,'book6','malayalam',200);
insert into books(book_id,book_name,language,price) values(7,'book7','english',700);
insert into books(book_id,book_name,language,price) values(8,'book8','hindi',200);
insert into books(book_id,book_name,language,price) values(9,'book9','hindi',100);