server:
  port: 8100
spring:
  application:
    name: message-producer
  # RabbitMQ properties
  rabbitmq:
    host: ec2-34-230-59-140.compute-1.amazonaws.com
    virtual-host: /
    port: 8080
    password: password
    username: user
    template:
      exchange: simple-exchange-235749
      default-receive-queue: simple-queue-235749
      routing-key: simple-routing-key-235749
