server:
  port : 8000

spring:
  datasource:
    url : jdbc:h2:mem:users
    driverClassName : org.h2.Driver
    username : root
    password : root
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto : update
#    show-sql : true
  h2:
    console:
      enabled : true
      path : /h2
    settings:
      web-allow-others : false

logging:
  level:
    root: INFO